export const squarePhrases = [
    "Can you please repeat that?",
    "Sorry, I couldn't log in",
    "I had connection issues",
    "Can you hear me?",
    "Can you see my screen?",
    "I think we got disconnected",
    "I'm on mute",
    "Can you please unmute yourself?",
    "Can you please share your screen?",
    "Can you please send that in an email?",
    "I'm running late",
    "Can we schedule another meeting?",
    "I'll have to call you back",
    "Can you please speak up?",
    "Can you please slow down?",
    "I think we're on different pages",
    "Can we schedule a follow-up call?",
    "I need to step away for a moment",
    "Can you please clarify that?",
    "I think we're getting off topic",
    "Can you please send me the agenda?",
    "I'll have to get back to you on that",
    "I think we're going in circles",
    "I'll have to check with my team",
]